// Generated by CoffeeScript 1.8.0
(function() {
  var myApp;

  myApp = angular.module('myApp', []);

  myApp.factory('Data', function() {
    return {
      message: "I'm data from a service"
    };
  });

  myApp.controller('FirstCtrl', function($scope, Data) {
    return $scope.data = Data;
  });

  myApp.controller('SecondCtrl', function($scope, Data) {
    $scope.data = Data;
    return $scope.reversedMessage = function(message) {
      return message.split("").reverse().join("");
    };
  });

}).call(this);
