// Generated by CoffeeScript 1.8.0
(function() {
  var myAppModule;

  myAppModule = angular.module('myApp', []);

  myAppModule.controller("StartUpController", function($scope) {
    $scope.funding = {
      startingEstimate: 0
    };
    $scope.computeNeeded = function() {
      return $scope.funding.needed = $scope.funding.startingEstimate * 10;
    };
    $scope.reset = function() {
      return $scope.funding.startingEstimate = 0;
    };
    $scope.requestFunding = function() {
      return window.alert("Sorry, please get more customers first");
    };
  });

}).call(this);
