// Generated by CoffeeScript 1.8.0
(function() {
  angular.module("finance2", []).factory("currencyConverter", function() {
    var currencyConverter;
    return new (currencyConverter = (function() {
      function currencyConverter() {
        this.currencies = ["USD", "EUR", "CNY"];
        this.usdToForeignRates = {
          USD: 1,
          EUR: 0.74,
          CNY: 6.09
        };
      }

      currencyConverter.prototype.convert = function(amount, inCurr, outCurr) {
        return amount * this.usdToForeignRates[outCurr] / this.usdToForeignRates[inCurr];
      };

      return currencyConverter;

    })());
  });

}).call(this);
