// Generated by CoffeeScript 1.8.0
(function() {
  angular.module("invoice2", ["finance2"]).controller('InvoiceController', (function() {
    function _Class($scope, currencyConverter) {
      this.$scope = $scope;
      this.currencyConverter = currencyConverter;
      this.qty = 1;
      this.cost = 2;
      this.inCurr = 'EUR';
      this.currencies = currencyConverter.currencies;
    }

    _Class.prototype.total = function(outCurr) {
      return this.currencyConverter.convert(this.qty * this.cost, this.inCurr, outCurr);
    };

    _Class.prototype.pay = function() {
      return window.alert("Thanks!");
    };

    return _Class;

  })());

}).call(this);
