// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('invoice1', []).controller('InvoiceController', (function() {
    function _Class($scope) {
      this.$scope = $scope;
      this.qty = 1;
      this.cost = 2;
      this.inCurr = "EUR";
      this.currencies = ["USD", "EUR", "CNY"];
      this.usdToForeignRates = {
        USD: 1,
        EUR: 0.74,
        CNY: 6.09
      };
    }

    _Class.prototype.total = function(outCurr) {
      return this.convertCurrency(this.qty * this.cost, this.inCurr, outCurr);
    };

    _Class.prototype.convertCurrency = function(amount, inCurr, outCurr) {
      return amount * this.usdToForeignRates[outCurr] / this.usdToForeignRates[inCurr];
    };

    _Class.prototype.pay = function() {
      return window.alert("Thanks");
    };

    return _Class;

  })());

}).call(this);
